const CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vTgw11TS3xBI37HrqoJmJSI1ZSy5mxhT6-9BBUzr3jj9119oUZwAIAI-caD4W3m0SwjQdE7Xd4Pazf_/pub?output=csv";
const CACHE_KEY = "lwh-load-board-data-v1";
const state = {rows:[],loads:[],filtered:[],view:"board",calendarMonth:new Date(new Date().getFullYear(),new Date().getMonth(),1),deferredInstall:null};
const $=id=>document.getElementById(id), clean=v=>String(v??"").trim(), upper=v=>clean(v).toUpperCase();
const number=v=>{const n=Number(String(v??"").replace(/,/g,""));return Number.isFinite(n)?n:0};
const dateKey=d=>!(d instanceof Date)||Number.isNaN(d.valueOf())?"":`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const fmtDate=d=>d instanceof Date&&!Number.isNaN(d)?new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(d):"";
const fmtNum=n=>new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(number(n));
const escapeHtml=s=>clean(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function parseDate(value){const s=clean(value);if(!s)return null;const d=new Date(s);if(!Number.isNaN(d.valueOf()))return d;const m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})/);if(m){let y=Number(m[3]);if(y<100)y+=2000;return new Date(y,Number(m[1])-1,Number(m[2]))}return null}
function parseCSV(text){const rows=[];let row=[],field="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],next=text[i+1];if(c=='"'&&quoted&&next=='"'){field+='"';i++}else if(c=='"')quoted=!quoted;else if(c==","&&!quoted){row.push(field);field=""}else if((c=="\n"||c=="\r")&&!quoted){if(c=="\r"&&next=="\n")i++;row.push(field);field="";if(row.some(v=>v!==""))rows.push(row);row=[]}else field+=c}if(field||row.length){row.push(field);rows.push(row)}const headers=(rows.shift()||[]).map(h=>clean(h).replace(/^\uFEFF/,""));return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]??""])))}
function pick(row,...names){const entries=Object.entries(row);for(const name of names){const exact=entries.find(([k])=>upper(k)===upper(name));if(exact)return exact[1]}return""}
function normalize(raw){return{date:parseDate(pick(raw,"CalendarDate","DeliveredDate","Date")),whse:clean(pick(raw,"WHSE","Warehouse")),direction:upper(pick(raw,"Direction")),customer:clean(pick(raw,"SubCust","Customer","SubCustNm")),pro:clean(pick(raw,"ProNumber","Pro Number","PRO")),relatedPro:clean(pick(raw,"RelatedPro","Related Pro")),billRef:clean(pick(raw,"BillToReference","Bill To Reference","BillToRefNum")),carrier:clean(pick(raw,"Carrier","CarrierName")),shipper:clean(pick(raw,"Shipper","ShipperName")),conName:clean(pick(raw,"ConName","Consignee")),status:clean(pick(raw,"Status")),item:clean(pick(raw,"ItemNm","Item","Item Number")),description:clean(pick(raw,"ItemDescription","Item Description","Description1")),units:number(pick(raw,"Units","UnitCount","Pallets")),qty:number(pick(raw,"ItemQty","Qty","Quantity")),instructions:clean(pick(raw,"Instructions")),comments:clean(pick(raw,"Comments")),raw}}
function makeLoadKey(r){const p=clean(pick(r.raw,"LoadKey"));return p||[dateKey(r.date),r.whse,r.direction,r.pro,r.billRef,r.relatedPro,r.customer].join("|")}
function groupLoads(rows){const map=new Map();rows.forEach(r=>{const key=makeLoadKey(r);if(!map.has(key))map.set(key,{key,date:r.date,whse:r.whse,direction:r.direction,customer:r.customer,pro:r.pro,relatedPro:r.relatedPro,billRef:r.billRef,carrier:r.carrier,shipper:r.shipper,conName:r.conName,status:r.status,instructions:r.instructions,comments:r.comments,items:[]});const load=map.get(key);if(r.item||r.units||r.qty){const itemKey=`${r.item}|${r.description}`,existing=load.items.find(i=>i.key===itemKey);if(existing){existing.units+=r.units;existing.qty+=r.qty}else load.items.push({key:itemKey,item:r.item||"Unspecified item",description:r.description,units:r.units,qty:r.qty})}});return[...map.values()].sort((a,b)=>(a.date?.valueOf()||0)-(b.date?.valueOf()||0))}
function loadMetrics(load){return{itemCount:load.items.length,units:load.items.reduce((s,i)=>s+i.units,0),qty:load.items.reduce((s,i)=>s+i.qty,0)}}
async function loadData(){ $("syncStatus").textContent="Refreshing published schedule…";$("refreshBtn").disabled=true;try{const joiner=CSV_URL.includes("?")?"&":"?";const response=await fetch(CSV_URL+joiner+"cacheBust="+Date.now(),{cache:"no-store"});if(!response.ok)throw new Error(`CSV request failed (${response.status})`);const text=await response.text();if(!text.trim())throw new Error("The published CSV was empty.");localStorage.setItem(CACHE_KEY,JSON.stringify({text,savedAt:new Date().toISOString()}));useCSV(text);$("syncStatus").textContent=`Live data refreshed ${new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}`;$("notice").hidden=true}catch(error){const cached=JSON.parse(localStorage.getItem(CACHE_KEY)||"null");if(cached?.text){useCSV(cached.text);$("syncStatus").textContent=`Offline copy from ${new Date(cached.savedAt).toLocaleString()}`;showNotice("The published Google Sheet could not be reached. Showing the last successfully downloaded copy.")}else{state.rows=[];state.loads=[];applyFilters();$("syncStatus").textContent="Unable to load published schedule";showNotice("The app could not read the published CSV. Confirm the Google Sheet remains published to the web as CSV.")}console.error(error)}finally{$("refreshBtn").disabled=false}}
function useCSV(text){const raw=parseCSV(text);state.rows=raw.map(normalize).filter(r=>r.date||r.pro||r.billRef||r.customer);state.loads=groupLoads(state.rows);populateFilters();applyFilters()}
function showNotice(message){$("notice").textContent=message;$("notice").hidden=false}
function populateFilters(){fillSelect("warehouseFilter",[...new Set(state.loads.map(x=>x.whse).filter(Boolean))].sort(),"All warehouses");fillSelect("statusFilter",[...new Set(state.loads.map(x=>x.status).filter(Boolean))].sort(),"All statuses")}
function fillSelect(id,values,first){const el=$(id),current=el.value;el.innerHTML=`<option value="">${first}</option>`+values.map(v=>`<option>${escapeHtml(v)}</option>`).join("");if(values.includes(current))el.value=current}
function applyFilters(){const q=upper($("searchInput").value),whse=$("warehouseFilter").value,direction=$("directionFilter").value,status=$("statusFilter").value,range=$("rangeFilter").value,today=new Date();today.setHours(0,0,0,0);state.filtered=state.loads.filter(load=>{if(whse&&load.whse!==whse)return false;if(direction&&load.direction!==direction)return false;if(status&&load.status!==status)return false;const d=load.date?new Date(load.date.getFullYear(),load.date.getMonth(),load.date.getDate()):null;if(range==="today"&&dateKey(d)!==dateKey(today))return false;if(range==="7"&&(!d||d<today||d>=new Date(today.getFullYear(),today.getMonth(),today.getDate()+7)))return false;if(range==="31"&&(!d||d<today||d>=new Date(today.getFullYear(),today.getMonth(),today.getDate()+31)))return false;if(range==="past"&&(!d||d>=today||d<new Date(today.getFullYear(),today.getMonth(),today.getDate()-91)))return false;if(q){const hay=upper([load.whse,load.direction,load.customer,load.pro,load.relatedPro,load.billRef,load.carrier,load.shipper,load.conName,load.status,load.instructions,load.comments,...load.items.flatMap(i=>[i.item,i.description])].join(" "));if(!hay.includes(q))return false}return true});renderAll()}
function renderAll(){renderKPIs();renderBoard();renderCalendar();renderTable();renderSummary()}
function renderKPIs(){const loads=state.filtered,inbound=loads.filter(x=>x.direction==="INBOUND").length,outbound=loads.filter(x=>x.direction==="OUTBOUND").length,units=loads.reduce((s,l)=>s+loadMetrics(l).units,0),qty=loads.reduce((s,l)=>s+loadMetrics(l).qty,0),unmatched=loads.filter(l=>!l.items.length).length,cards=[["Loads",loads.length],["Inbound",inbound],["Outbound",outbound],["Units",fmtNum(units)],["Quantity",fmtNum(qty)],["No item match",unmatched]];$("kpis").innerHTML=cards.map(([label,value])=>`<article class="kpi"><div class="label">${label}</div><div class="value">${value}</div></article>`).join("")}
function renderBoard(){const host=$("boardView");if(!state.filtered.length){host.innerHTML=$("emptyTemplate").innerHTML;return}const groups=new Map();state.filtered.forEach(l=>{const key=l.whse||"Warehouse not listed";if(!groups.has(key))groups.set(key,[]);groups.get(key).push(l)});host.innerHTML=[...groups.entries()].map(([whse,loads])=>`<section class="warehouse-group"><div class="group-heading"><h2>${escapeHtml(whse)}</h2><span>${loads.length} load${loads.length===1?"":"s"}</span></div><div class="load-grid">${loads.map(loadCard).join("")}</div></section>`).join("");host.querySelectorAll("[data-load]").forEach(b=>b.addEventListener("click",()=>openLoad(b.dataset.load)))}
function loadCard(load){const m=loadMetrics(load),completed=upper(load.status).includes("COMPLETED");return`<article class="load-card ${load.direction==="OUTBOUND"?"outbound":""} ${completed?"completed":""}"><button class="card-open" data-load="${escapeHtml(load.key)}"><div class="card-top"><div><div class="date">${escapeHtml(fmtDate(load.date))}</div><span class="status-pill">${escapeHtml(load.status||"Status not listed")}</span></div><div class="direction">${escapeHtml(load.direction||"UNKNOWN")}</div></div><div class="card-body"><h3 class="customer">${escapeHtml(load.customer||load.conName||"Customer not listed")}</h3><div class="reference"><b>Pro</b><span>${escapeHtml(load.pro||"—")}</span><b>Bill To Ref</b><span>${escapeHtml(load.billRef||"—")}</span><b>Carrier</b><span>${escapeHtml(load.carrier||"—")}</span></div></div><div class="card-items"><div class="metric"><b>${fmtNum(m.itemCount)}</b><span>Items</span></div><div class="metric"><b>${fmtNum(m.units)}</b><span>Units</span></div><div class="metric"><b>${fmtNum(m.qty)}</b><span>Qty</span></div></div></button></article>`}
function renderTable(){const host=$("tableView");if(!state.filtered.length){host.innerHTML=$("emptyTemplate").innerHTML;return}const rows=[];state.filtered.forEach(load=>{if(load.items.length)load.items.forEach(item=>rows.push({load,item}));else rows.push({load,item:{item:"",description:"",units:0,qty:0}})});host.innerHTML=`<div class="table-wrap"><table><thead><tr><th>Date</th><th>WHSE</th><th>Direction</th><th>Status</th><th>Customer</th><th>Pro</th><th>Bill To Ref</th><th>Item</th><th>Description</th><th>Units</th><th>Qty</th><th>Carrier</th></tr></thead><tbody>${rows.map(x=>{const l=x.load,i=x.item;return`<tr><td>${escapeHtml(fmtDate(l.date))}</td><td>${escapeHtml(l.whse)}</td><td>${escapeHtml(l.direction)}</td><td>${escapeHtml(l.status)}</td><td>${escapeHtml(l.customer)}</td><td>${escapeHtml(l.pro)}</td><td>${escapeHtml(l.billRef)}</td><td>${escapeHtml(i.item)}</td><td>${escapeHtml(i.description)}</td><td>${fmtNum(i.units)}</td><td>${fmtNum(i.qty)}</td><td>${escapeHtml(l.carrier)}</td></tr>`}).join("")}</tbody></table></div>`}
function renderCalendar(){const host=$("calendarView"),month=state.calendarMonth,y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay()),byDate=new Map();state.filtered.forEach(l=>{const k=dateKey(l.date);if(!byDate.has(k))byDate.set(k,[]);byDate.get(k).push(l)});let cells="";for(let i=0;i<42;i++){const d=new Date(start.getFullYear(),start.getMonth(),start.getDate()+i),list=byDate.get(dateKey(d))||[];cells+=`<div class="calendar-day ${d.getMonth()!==m?"muted":""} ${dateKey(d)===dateKey(new Date())?"today":""}"><div class="day-number">${d.getDate()}</div>${list.slice(0,4).map(l=>`<button class="day-load" data-load="${escapeHtml(l.key)}">${escapeHtml(l.whse)} · ${escapeHtml(l.customer||l.pro||l.billRef)}</button>`).join("")}${list.length>4?`<div class="day-load">+${list.length-4} more</div>`:""}</div>`}host.innerHTML=`<div class="calendar-controls"><button id="prevMonth">← Previous</button><h2>${new Intl.DateTimeFormat("en-US",{month:"long",year:"numeric"}).format(month)}</h2><button id="nextMonth">Next →</button></div><div class="calendar-grid">${["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=>`<div class="day-name">${x}</div>`).join("")}${cells}</div>`;$("prevMonth").onclick=()=>{state.calendarMonth=new Date(y,m-1,1);renderCalendar()};$("nextMonth").onclick=()=>{state.calendarMonth=new Date(y,m+1,1);renderCalendar()};host.querySelectorAll("[data-load]").forEach(b=>b.addEventListener("click",()=>openLoad(b.dataset.load)))}
function renderSummary(){const host=$("summaryView");if(!state.filtered.length){host.innerHTML=$("emptyTemplate").innerHTML;return}host.innerHTML=`<div class="summary-grid">${summaryBlock("By Warehouse",summarize("whse"))}${summaryBlock("By Customer",summarize("customer"))}${summaryBlock("By Item",summarizeItems())}</div>`}
function summarize(field){const map=new Map();state.filtered.forEach(l=>{const k=l[field]||"Not listed",m=loadMetrics(l),v=map.get(k)||{name:k,loads:0,units:0,qty:0};v.loads++;v.units+=m.units;v.qty+=m.qty;map.set(k,v)});return[...map.values()].sort((a,b)=>b.loads-a.loads)}
function summarizeItems(){const map=new Map();state.filtered.forEach(l=>l.items.forEach(i=>{const k=i.item||"Not listed",v=map.get(k)||{name:k,loads:0,units:0,qty:0,keys:new Set()};v.keys.add(l.key);v.loads=v.keys.size;v.units+=i.units;v.qty+=i.qty;map.set(k,v)}));return[...map.values()].sort((a,b)=>b.loads-a.loads).slice(0,50)}
function summaryBlock(title,rows){return`<section class="summary-card"><h2>${title}</h2><div class="summary-row head"><span>Name</span><span>Loads</span><span>Units</span><span>Qty</span></div>${rows.map(r=>`<div class="summary-row"><span>${escapeHtml(r.name)}</span><span>${fmtNum(r.loads)}</span><span>${fmtNum(r.units)}</span><span>${fmtNum(r.qty)}</span></div>`).join("")}</section>`}
function openLoad(key){const l=state.loads.find(x=>x.key===key);if(!l)return;const m=loadMetrics(l);$("dialogContent").innerHTML=`<div class="dialog-inner"><h2>${escapeHtml(l.direction||"Load")} — ${escapeHtml(l.customer||l.pro||l.billRef)}</h2><div class="detail-grid">${detail("Date",fmtDate(l.date))}${detail("Warehouse",l.whse)}${detail("Status",l.status)}${detail("Carrier",l.carrier)}${detail("Pro Number",l.pro)}${detail("Related Pro",l.relatedPro)}${detail("Bill To Reference",l.billRef)}${detail("Consignee",l.conName)}${detail("Shipper",l.shipper)}${detail("Load Totals",`${m.itemCount} items · ${fmtNum(m.units)} units · ${fmtNum(m.qty)} qty`)}</div><section class="item-list"><h3>Items</h3>${l.items.length?l.items.map(i=>`<div class="item-row"><div><b>${escapeHtml(i.item)}</b><br><small>${escapeHtml(i.description)}</small></div><div><b>${fmtNum(i.units)}</b><br><small>Units</small></div><div class="qty"><b>${fmtNum(i.qty)}</b><br><small>Quantity</small></div></div>`).join(""):"<p>No matched transaction items are published for this load yet.</p>"}</section>${l.instructions?`<div class="notes"><b>Instructions</b><br>${escapeHtml(l.instructions)}</div>`:""}${l.comments?`<div class="notes"><b>Comments</b><br>${escapeHtml(l.comments)}</div>`:""}</div>`;$("loadDialog").showModal()}
function detail(label,value){return`<div class="detail"><span>${label}</span><b>${escapeHtml(value||"—")}</b></div>`}
document.querySelectorAll(".toolbar input,.toolbar select").forEach(el=>el.addEventListener("input",applyFilters));
document.querySelectorAll(".tab").forEach(tab=>tab.addEventListener("click",()=>{state.view=tab.dataset.view;document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t===tab));["board","calendar","table","summary"].forEach(v=>$(v+"View").hidden=v!==state.view)}));
$("refreshBtn").onclick=loadData;$("closeDialog").onclick=()=>$("loadDialog").close();$("loadDialog").addEventListener("click",e=>{if(e.target===$("loadDialog"))$("loadDialog").close()});
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();state.deferredInstall=e;$("installBtn").hidden=false});
$("installBtn").onclick=async()=>{if(!state.deferredInstall)return;state.deferredInstall.prompt();await state.deferredInstall.userChoice;state.deferredInstall=null;$("installBtn").hidden=true};
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
loadData();
